### ISSUE TITLE
Classes attribute should be handled as a special attribute

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/kotlinx.html-plugin#14]
See https://github.com/kotlin/kotlinx.html/wiki/Elements-CSS-classes

By default, and for element builder functions that have optional classes argument, generate code should be: 

```
div(classes = "container left tree") {
}
```

**Comment by xal** [comment]
I moved classes to the constructor in PR
But I didn't change other tags which have other constructor arguments, for example, `href` for `a`
```
 a(href = "https://kotlinlang.org") {
}
```
@gzoritchak Should I also iterate over all kotlinx tags constructors arguments and implement them as `class`?

**Comment by gzoritchak** [comment]
No, it's fine like this. Class is a special one because of its very frequent usage.

**Comment by gzoritchak** [comment]
Fixed by https://github.com/data2viz/kotlinx.html-plugin/pull/15
